site_title = "ArxivDaily"
limit_days = 7
# cache_url = "https://linlinwang1997.github.io/ArxivDaily/cache.json"

[[sources]]
limit = 100
category = "math.AP"
title = "Analysis of PDEs"

[[sources]]
limit = 100
category = "math.FA"
title = "Functional Analysis"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_meeting = "scripts/highlight_meeting.rhai"
